version: "3.6"
services:

  db:
    container_name: qiskitflow-db
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: qiskitflow
    ports:
    - 5432:5432

  server:
    container_name: qiskitflow-server
    image: icekhan/qiskitflow-backend:latest
    command: sh -c "until pg_isready --username=postgres --host=db; do sleep 1; done; python manage.py migrate && python manage.py initadmin && gunicorn qiskitflow_backend.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      DEBUG: 'False'
      ALLOWED_HOSTS: "*,"
      DB_NAME: qiskitflow
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      STATIC_URL: "/static/"
      DJANGO_ADMINS: "admin,admin,nonexistingemail@someserver.ru"
    depends_on:
      - db

  ui:
    container_name: qiskitflow-ui
    image: icekhan/qiskitflow-ui:latest
    ports:
      - "3000:80"
