# Generated by Django 3.1.2 on 2020-10-08 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_measure_measurement_metric_parameter_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='main.measurement'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='main.run'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='main.run'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='main.run'),
        ),
        migrations.AlterField(
            model_name='run',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='main.experiment'),
        ),
    ]
