# Generated by Django 3.1.2 on 2021-02-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
