# Generated by Django 3.1.2 on 2020-10-28 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_experiment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measuremententry',
            old_name='run',
            new_name='measurement',
        ),
    ]
