# Generated by Django 3.1.2 on 2021-02-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210220_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='version',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
