# Generated by Django 3.1.2 on 2020-10-28 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_measurement_entry_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measuremententry',
            name='measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.measurement'),
        ),
    ]
