# Generated by Django 3.1.2 on 2021-03-02 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_run_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='StateVector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_vectors', to='core.run')),
            ],
        ),
        migrations.CreateModel(
            name='ComplexNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real', models.FloatField()),
                ('img', models.FloatField(default=0.0)),
                ('state_vector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vector', to='core.statevector')),
            ],
        ),
    ]
