name: Dockerhub release

on: [push]
  # release:
  #   types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build and push backend
        uses: docker/build-push-action@v2
        with:
          context: ./backend/
          file: _Dockerfile
          push: true
          tags: icekhan/qiskitflow-backend:latest
          #,icekhan/qiskitflow-backend:$release_version
      -
        name: Build and push ui
        uses: docker/build-push-action@v2
        with:
          context: ./ui/
          push: true
          tags: icekhan/qiskitflow-ui:latest
          #,icekhan/qiskitflow-backend:$release_version
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}